### ISSUE TITLE
[Pkgs] Allow assertion jobs to work with arrays / lists

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1027]
@nwinkler commented on [Tue Jun 14 2016](https://github.com/eris-ltd/eris-pm/issues/143)
- [Docker version 1.11.1, build 5604cbe] `docker version`
- [Eris CLI Version: 0.11.4] `eris version`
- [ ] `go version` (if applicable)
- [docker-machine version 0.7.0, build a650a40] `docker-machine version` (if applicable / !linux)
- [OS X 10.11.5] operating system details (osx/windows/linux)

Eris is not replacing the first variable in a list as part of an `assert` job. Steps to reproduce:

Using the following `epm.yaml`:

``` yaml
jobs:

- name: setStorageBaseIsbn
  job:
    set:
      val: "1234"

- name: setStorageBaseName
  job:
    set:
      val: "Moby"

- name: assertStorageList
  job:
    assert:
      key: (1234 Moby)
      relation: eq
      val: ($setStorageBaseIsbn $setStorageBaseName)
```

Running this fails with the following error:

```
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 setStorageBaseIsbn
Executing Job                                 setStorageBaseName
Executing Job                                 assertStorageList
Assertion Failed                              (1234 Moby) == ($setStorageBaseIsbn Moby)
assertion failed
```

The expected outcome is that it would replace the `$setStorageBaseIsbn` with `1234`. The leading `(` seems to throw the replacement off.
