### ISSUE TITLE
[PM] a pre-processor / linter to catch bad syntax in epm.yaml

### ISSUE THREAD

**Issue by zramsay** [monax/cli#1256]
for example:
```
- name: getOverallMean
  job:
    call:
      destination: $deployStatistics
      function: calculateOverallMean
      data:
        - [14,34,54]
```
works as expected whereas
```
- name: getOverallMean
  job:
    call:
    destination: $deployStatistics
    function: calculateOverallMean
    data:
      - [14,34,54]
```
throws no warning whatsoever and instead _ignores the job completely_! An error should be thrown for this bad syntax and `eris pkgs do` should fail accordingly
